### ISSUE TITLE
Pressure Testing Environment with Delta 5 mm HG

### ISSUE THREAD

**Issue by yashasaxena** [Duke-BME-Design/Ureter#14]
Develop a simple pressure testing environment to determine how our circuit responds to change

**Comment by yashasaxena** [comment]
maybe? https://jlbrooks.co.uk/media/catalog/product/cache/1/image/800x800/9df78eab33525d08d6e5fb8d27136e95/d/-/d-capri-ora200.jpg

**Comment by yashasaxena** [comment]
https://www.amazon.com/dp/B01MCZ646P/ref=sspa_dk_detail_0?pd_rd_i=B010IS0OUE&pd_rd_wg=OSrkJ&pd_rd_r=7CQC8KMNRDV56MWWC14F&pd_rd_w=dUtea&th=1

**Comment by yashasaxena** [comment]
Going to be a U-tube manometer with one end capped off with a pressure modulating piston, design included in lab notebook, we can use the piston to mimic peristalsis pressure wave-form as well

**Comment by yashasaxena** [comment]
had some downtime while working at the co-lab, testing out this print 
<img width="564" alt="screen shot 2018-02-23 at 8 02 42 pm" src="https://user-images.githubusercontent.com/8584289/36623684-b8d19fa4-18d4-11e8-948a-d7a279289d73.png">

**Comment by kmc97** [comment]
how will this work? is this just holding the tube in place?

**Comment by yashasaxena** [comment]
ya, like a way to prop it vertical so we can assess height difference
