### ISSUE TITLE
Develop Test Plan for Pressure Testing

### ISSUE THREAD

**Issue by yashasaxena** [Duke-BME-Design/Ureter#15]
make plan for pressure testing to validate our circuit as ready

**Comment by yashasaxena** [comment]
some ideas: 
- scenarios for testing (Dr. P's suggestion -> randomizing pressure val order, high to low, low to high, introduction of physiological factors - peristalsis, saline) 
- analysis of timing...capacitor induced (how long does it take for pressure values to be registered?),
- signal-to-noise ratio (set an ideal value given the magnitudes of intended readings and compare)

**Comment by kmc97** [comment]
see excel sheet... there definitely is some aspect of timing delay. visually it appears to be on the order of tens of millivolts and is corrected within about 3 seconds (estimation)

**Comment by yashasaxena** [comment]
ok great, i'll work on this tonight

**Comment by yashasaxena** [comment]
Located in google drive: 
Team Ureter > Spring 2018 > 2/11 Test Plan
