### ISSUE TITLE
Stand for U-tube Manometer

### ISSUE THREAD

**Issue by yashasaxena** [Duke-BME-Design/Ureter#23]
Something to bolster the u-tube when we modulate pressures, set location based known pressure values 
https://www.thingiverse.com/thing:1205032

**Comment by yashasaxena** [comment]
Piston that will be modulating pressure in U-tube manometer
![img_7355 2](https://user-images.githubusercontent.com/8584289/36346104-d8978462-1405-11e8-8a0b-724966053144.JPG)

**Comment by yashasaxena** [comment]
Making brackets for this, but other than that it should be good to go for our dynamic range
![img_9232](https://user-images.githubusercontent.com/8584289/36806998-caa4f37a-1c8f-11e8-9638-74228f2de5ed.JPG)
![img_2305](https://user-images.githubusercontent.com/8584289/36807004-cc2d0fc0-1c8f-11e8-9c0f-a37fc1253bcd.JPG)

**Comment by kmc97** [comment]
that looks good! like the duck tape lol
