### ISSUE TITLE
Optical Encoder System

### ISSUE THREAD

**Issue by yashasaxena** [Duke-BME-Design/Ureter#24]
start thinking about optical encoder to track catheter distance; talk to Matt Brown about existing; think about how we will attach to catheter

**Comment by yashasaxena** [comment]
@mlp6 did you say we could trigger the encoder as on/off, so we could control when it starts and stops taking measurements?

**Comment by mlp6** [comment]
Yes... but that is done more by the entity controlling the encoder than the encoder itself.  I can send you some details on the encoder we use in the lab if you would like that as a starting point.

**Comment by yashasaxena** [comment]
@mlp6 yes please! yeah i guess it might be more when the microcontroller decides to collect whatever data is currently on the device through the analog output, and then we can always use the difference of the data first and last collected as the length measurement

**Comment by yashasaxena** [comment]
@mlp6 matt says we will have to order our own as there are no free ones: https://www.usdigital.com/products/encoders/incremental/linear/LIN 
with the encoder at the bottom of the page

how do we go about ordering? also, would you say this is something we can incorporate with the cystoscope somehow?

**Comment by yashasaxena** [comment]
So, I just met with Dr. Sharifi, and he does not need the measurement process to be automated. He only wants an auditory signal, so the surgeon can mark the catheter himself physically. Will open another issue for that

**Comment by mlp6** [comment]
https://www.digikey.com/en/product-highlight/b/broadcom-semi/aedr-871x-digital-aedr-872x-analog-encoder-devices?utm_adgroup=xGeneral&gclid=Cj0KCQiAw9nUBRCTARIsAG11eiftp3r_CSIzVyAXj3QGxNrjH_8n7sbPS70rUZKSddcICkXr3CwJlhsaAsi0EALw_wcB

**Comment by mlp6** [comment]
I am going to upload some of our associated code to GitHub (just need to check if I can keep it public or need to make it private).

**Comment by mlp6** [comment]
You should all have access now to: https://github.com/mlp6/prostate_probe_rotation  The specific code of interest is probably `src/encoder.py`.

**Comment by yashasaxena** [comment]
THANKS! So, in terms of getting the encoder, should I put in a formal request to either you or Matt?

**Comment by mlp6** [comment]
Matt can take care of this for you.

**Comment by kmc97** [comment]
ordered.
