### ISSUE TITLE
Active offset 

### ISSUE THREAD

**Issue by kmc97** [Duke-BME-Design/Ureter#25]
offset in feedback loop that automatically adjusts to catheter fluctuations. Keeps the low bound at .1V ish

**Comment by deeptig94** [comment]
The voltage values before the final stage of amplification should be read and offset so that they are no less than -0.1 V while there is no change in pressure. When there is a change in pressure it needs to be deactivated so that the voltage changes with pressure change.

**Comment by deeptig94** [comment]
Active offset - Press a button when the catheter is in the ureter (past the UVJ) to zero out offset
Alternative - Have a knob that can be turned to zero out offset
