### ISSUE TITLE
Uniform Pressure Chamber

### ISSUE THREAD

**Issue by kmc97** [Duke-BME-Design/Ureter#3]
Ensure Chamber is in correct physiological dynamic range (maybe 30 mm Hg)

**Comment by yashasaxena** [comment]
No manometer until tomorrow! Will try to tackle this on West campus tomorrow

**Comment by kmc97** [comment]
Uniform pressure chamber can be held at 30 mm Hg

**Comment by kmc97** [comment]
anatomically we are looking at a resting pressure at 5 mm Hg.  Yasha is confirming with Dr. Sharifi

**Comment by yashasaxena** [comment]
Redundant with issue #17
