### ISSUE TITLE
set up rasberry pi

### ISSUE THREAD

**Issue by kmc97** [Duke-BME-Design/Ureter#30]
get it up and running

**Comment by kmc97** [comment]
looks like were going to have to figure out a way how to read in analog signals with an MCP3008 thing or some discharge circuit 

https://www.allaboutcircuits.com/projects/building-raspberry-pi-controllers-part-5-reading-analog-data-with-an-rpi/

**Comment by yashasaxena** [comment]
This hasn't happened yet because we're having monitor hook up issues, so its currently blocked

**Comment by yashasaxena** [comment]
Monitor hook up issues resolved, now we can move forward by setting up ADC chip, and uploading code

**Comment by yashasaxena** [comment]
The MCP3008 chip is reading voltage values correctly, tested by reading outputs of a high frequency 1kHZ sawtooth 0-1V wave, voltage values look right 
![img_9923](https://user-images.githubusercontent.com/8584289/38222376-5d83f7e0-36b2-11e8-80d5-529cc14762c2.JPG)

**Comment by yashasaxena** [comment]
we have and sd card,  the tv and the long hdmi cable so we can wire out from our station to the monitor, github repo is on there now so we can push and pull code too
