### ISSUE TITLE
Manometer for independent pressure measurement

### ISSUE THREAD

**Issue by mlp6** [Duke-BME-Design/Ureter#4]
see if secondary pressure transducer circuit may be used to verify manometer/if its worth it. Is there a higher resolution manometer?

**Comment by yashasaxena** [comment]
At chesterfield, the manometer is actually still on west campus. Double fail lol

**Comment by kmc97** [comment]
Jason mentioned other labs may have other manometers, matt brown has no other manometers. looking to perhaps set up a circuit with pressure transducing resistors to get a live time dependent pressure feed that is calibrated to standard manometer

**Comment by yashasaxena** [comment]
Closed with #11
