### ISSUE TITLE
Python Code for Raspberry Pi

### ISSUE THREAD

**Issue by yashasaxena** [Duke-BME-Design/Ureter#40]
Have some code uploaded in "rPi_codeBase" branch
need to QC once we finish setting up Pi 

should plug in analog signal from catheter into Channel 0 of ADC chip

**Comment by yashasaxena** [comment]
analog values are being read properly, but i was getting all zeros for my moving average so i need to double check what's going on there

**Comment by kmc97** [comment]
reading encoder position and voltages-- code pushed to branch

**Comment by kmc97** [comment]
sos @mlp6 @jl532 @yashasaxena @deeptig94 cant push the code from the pi to git.... or pull for that matter-- error looks like this 
![pierror](https://user-images.githubusercontent.com/32279493/38757834-7881f942-3f3c-11e8-84dd-5be222557c0f.jpg)

**Comment by kmc97** [comment]
im gonna retype and save to my local computer just in case the pi doesn't save the data.... anyways, i have the catheter voltages being exported into a csv file-- so we can use this to graph since matplotlib hates me and my poor computer

**Comment by kmc97** [comment]
going to close this and make more specific tasks
