### ISSUE TITLE
Buy Parts

### ISSUE THREAD

**Issue by yashasaxena** [Duke-BME-Design/Ureter#43]
- multiple battery packs (Yasha has 4.5 V ones that can be used for the catheter)
- new encoder strip

**Comment by kmc97** [comment]
emailed matt

**Comment by yashasaxena** [comment]
@kmc97 think you did this!

**Comment by kmc97** [comment]
ya still haven't gotten them tho

**Comment by kmc97** [comment]
parts recieved
