### ISSUE TITLE
Encoder detection validation

### ISSUE THREAD

**Issue by kmc97** [Duke-BME-Design/Ureter#51]
Record voltages and UVJ/orifice output to verify and validate that the rising/falling edges correspond to the issuance of a declared encoder position. this can be done by exporting csv and observing if the UVJ/orifice output changes when a voltage threshold is switched

**Comment by kmc97** [comment]
![image](https://user-images.githubusercontent.com/32279493/38892013-100eda9a-4254-11e8-90ee-c8670fc01f4a.png)

**Comment by kmc97** [comment]
as you can see, the blue line (UVJ-rising edge) changes at the rising edge of the voltage pulse-- the encoder correctly identifies this edge. the orange line (orifice) changes at the falling edge.  This confirms that the algorithm to detected relative encoder position is VERIFIED

**Comment by kmc97** [comment]
thoughts @yashasaxena @deeptig94 ?

**Comment by yashasaxena** [comment]
Yeah that looks right on the money.
