### ISSUE TITLE
Observe Signal to Noise Reading

### ISSUE THREAD

**Issue by kmc97** [Duke-BME-Design/Ureter#6]
Figure out the basis of the Signal to Noise ratio. A baseline to improve

**Comment by kmc97** [comment]
delayed due to reconstruction of circuit. in process of protoboarding to reduce some of the bouncy signal

**Comment by kmc97** [comment]
now that pressure circuit is calibrated, will move on to this next

**Comment by kmc97** [comment]
tried to institute 60 hz notch filter, took away noise but voltage response is MAJOR delayed.. honestly doesnt fluctuate that significantly-- may be ok
<img width="308" alt="noise_voltage" src="https://user-images.githubusercontent.com/32279493/36054358-e843288c-0dc3-11e8-8b7b-e7cd51ee1081.png">

**Comment by kmc97** [comment]
if SNR is calculated by the mean/st.dev then the circuit has a SNR of 4.5 and the catheter has a SNR or 42... which seems sort of incorrect

**Comment by yashasaxena** [comment]
We could use FT to calculate SNR? I think in the time domain we would want to have the clean signal compared to the dirty signal minus the clean signal

**Comment by yashasaxena** [comment]
We might also try getting the reading at 0 pressure and considering that to be just the noise?
