### ISSUE TITLE
Re-do Protoboard/Breadboard for Catheter Circuit

### ISSUE THREAD

**Issue by yashasaxena** [Duke-BME-Design/Ureter#7]
In light of our missing protoboard, need to redo this!
Deepti - half wheatstone, instrumentation
Yasha - low pass

**Comment by kmc97** [comment]
Jumping signal--- most likely due to potentiometer making poor contact with bread board/not very precise.  Looking to use a more exact potentiometer and protoboard to mitigate this issue.  will come back tomorrow morning and make the protoboard for the catheter

**Comment by kmc97** [comment]
added offset removal and additional low pass filter amplification. Dynamic range: 1.5 V per 140 mm Hg

**Comment by yashasaxena** [comment]
breaking this down into smaller issues
